### ISSUE TITLE
Review all of the pages.

### ISSUE THREAD

**Issue by BlakeDalmas** [BlakeDalmas/webdev_final#8]

**Comment by BlakeDalmas** [comment]
I finished editing mine so someone can review the pc pages if you want.

**Comment by BrysonCook** [comment]
Reviewed PC pages, everything seemed fine although you might need to display your links to the images.

**Comment by BlakeDalmas** [comment]
I added sources/links to the pages and images, I'll push the changes later today.

**Comment by treychumbley** [comment]
All pages have been reviewed.
